export const API_ROUTES = {
  v1: {
    auth: {
      register: '/auth/register',
      login: '/auth/login',
      google: '/auth/google',
      logout: '/auth/logout',
      refresh: '/auth/refresh',
      password: {
        change: '/auth/password/change',
        reset: '/auth/password/reset',
      },
    },
    api: {
      base: '/api',
      users: {
        base: '/api/users',
        list: '/api/users',
        detail: (id: number) => `/api/users/${id}`,
      },
      employees: {
        base: '/api/employees',
        list: '/api/employees',
        detail: (id: number) => `/api/employees/${id}`,
        resign: (id: number) => `/api/employees/${id}/status`,
        validateUnique: '/api/employees/validate-unique',
        documents: {
          base: '/api/employees/documents',
          list: (id: number) => `/api/employees/${id}/documents`,
          upload: (id: number) => `/api/employees/${id}/documents`,
          delete: (id: number, documentId: number) =>
            `/api/employees/${id}/documents/${documentId}`,
        },
      },
      locations: {
        list: '/api/locations',
        detail: (id: string) => `/api/locations/${id}`,
        create: '/api/locations',
        update: (id: string) => `/api/locations/${id}`,
        delete: (id: string) => `/api/locations/${id}`,
      },
      workSchedules: {
        base: '/api/work-schedules',
        list: '/api/work-schedules',
        detail: (id: number) => `/api/work-schedules/${id}`,
        create: '/api/work-schedules',
        update: (id: number) => `/api/work-schedules/${id}`,
        delete: (id: number) => `/api/work-schedules/${id}`,
      },
      checkClockOverview: {
        list: '/api/check-clock/overview',
        detail: (id: number | string) => `/api/check-clock/${id}`,
        create: '/api/check-clock/overview',
        update: (id: number | string) => `/api/check-clock/${id}`,
        delete: (id: number | string) => `/api/check-clock/${id}`,
        approvalList: '/api/check-clock/approval',
        approveReject: (id: number | string) => `/api/check-clock/approval/${id}`,
        employeeRecords: (employeeId: string) => `/api/employees/${employeeId}/check-clock`,
      },
      documents: {
        base: '/api/documents',
        upload: '/api/documents/upload',
        list: '/api/documents',
        delete: (id: number) => `/api/documents/${id}`,
      },
      checkclockSettings: {
        list: '/api/checkclock-settings/',
        detail: (id: string) => `/api/checkclock-settings/${id}`,
        create: '/api/checkclock-settings',
        update: (id: string) => `/api/checkclock-settings/${id}`,
        delete: (id: string) => `/api/checkclock-settings/${id}`,
        byEmployee: (employeeId: string) => `/api/checkclock-settings/employee/${employeeId}`,
      },
      leaveRequests: {
        base: '/api/leave-requests',
        list: '/api/leave-requests',
        detail: (id: number) => `/api/leave-requests/${id}`,
        create: '/api/leave-requests',
        update: (id: number) => `/api/leave-requests/${id}`,
        delete: (id: number) => `/api/leave-requests/${id}`,
        my: '/api/leave-requests/my',
        status: (id: number) => `/api/leave-requests/${id}/status`,
      },
    },
  },
} as const;
