name: Deploy Golang to Azure

on:
    push:
        branches:
            - main
        paths:
            - "apps/backend/**"
            - ".github/workflows/deploy-be.yml"
            - "infrastructure/docker/backend/Dockerfile"

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        environment: production

        steps:
            - uses: actions/checkout@v3

            - name: Set up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to Azure Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
                  username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
                  password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

            - name: Build and push backend image
              id: docker_build
              uses: docker/build-push-action@v4
              with:
                  context: .
                  file: ./infrastructure/docker/backend/Dockerfile
                  push: true
                  tags: ${{ secrets.AZURE_CONTAINER_REGISTRY }}/my-backend-app:${{ github.sha }},${{ secrets.AZURE_CONTAINER_REGISTRY }}/my-backend-app:latest
                  cache-from: type=registry,ref=${{ secrets.AZURE_CONTAINER_REGISTRY }}/my-backend-app:latest
                  cache-to: type=inline

            - name: Login to Azure (Needed if you use Azure CLI commands directly)
              uses: azure/login@v1
              with:
                creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: Deploy to Azure Web App
              uses: azure/webapps-deploy@v2
              with:
                  app-name: hrisbackendpbl
                  images: ${{ secrets.AZURE_CONTAINER_REGISTRY }}/my-backend-app:${{ github.sha }}
                  publish-profile: ${{ secrets.AZURE_BACKEND_PUBLISH_PROFILE }}
