name: Deploy Next.js to Azure

on:
    push:
        branches:
            - main
        paths:
            - "apps/frontend/**"
            - ".github/workflows/deploy-fe.yml"
            - "infrastructure/docker/docker-compose.yml"
            - "infrastructure/docker/frontend/Dockerfile"

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to Azure
              uses: azure/login@v1
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: Login to Azure Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
                  username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
                  password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

            - name: Build and push frontend image
              uses: docker/build-push-action@v4
              with:
                  context: .
                  file: ./infrastructure/docker/frontend/Dockerfile
                  push: true
                  tags: ${{ secrets.AZURE_CONTAINER_REGISTRY }}/hris-frontend-sukamaju123:${{ github.sha }},${{ secrets.AZURE_CONTAINER_REGISTRY }}/hris-frontend-sukamaju123:latest
                  cache-from: type=registry,ref=${{ secrets.AZURE_CONTAINER_REGISTRY }}/hris-frontend-sukamaju123:latest
                  cache-to: type=inline

            - name: Deploy to Azure Web App
              uses: azure/webapps-deploy@v2
              with:
                  app-name: hris-frontend-sukamaju123
                  images: ${{ secrets.AZURE_CONTAINER_REGISTRY }}/hris-frontend-sukamaju123:${{ github.sha }}
                  publish-profile: ${{ secrets.AZURE_FRONTEND_PUBLISH_PROFILE }}
