name: Deploy Next.js to Azure

on:
    push:
        branches:
            - main
        paths:
            - "apps/frontend/**"
            - ".github/workflows/deploy-fe.yml"
            - "infrastructure/docker/frontend/Dockerfile"

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        environment: production

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to Azure CLI
              uses: azure/login@v1
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: Login to Azure Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
                  username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
                  password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

            - name: Build and push frontend image
              uses: docker/build-push-action@v4
              with:
                  context: .
                  file: ./infrastructure/docker/frontend/Dockerfile
                  push: true
                  tags: ${{ secrets.AZURE_CONTAINER_REGISTRY }}/my-frontend-app:${{ github.sha }},${{ secrets.AZURE_CONTAINER_REGISTRY }}/my-frontend-app:latest
                  cache-from: type=registry,ref=${{ secrets.AZURE_CONTAINER_REGISTRY }}/my-frontend-app:latest
                  cache-to: type=inline
                  build-args: |
                      NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
                      NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
                      NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}

            - name: Deploy to Azure Container Apps
              uses: azure/container-apps-deploy-action@v1
              with:
                  resourceGroup: ${{ secrets.AZURE_RESOURCE_GROUP_NAME }}
                  containerAppName: ${{ secrets.AZURE_FRONTEND_CONTAINER_APP_NAME }}
                  imageToDeploy: ${{ secrets.AZURE_CONTAINER_REGISTRY }}/my-frontend-app:${{ github.sha }}
