name: Trigger auto deployment for hrispblfrontend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/hrispblfrontend-AutoDeployTrigger-cd7cb891-5d20-4a74-8650-360494516c1a.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.HRISPBLFRONTEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.HRISPBLFRONTEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.HRISPBLFRONTEND_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/infrastructure/docker/frontend
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: hrispblregistry.azurecr.io
          registryUsername: ${{ secrets.HRISPBLFRONTEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.HRISPBLFRONTEND_REGISTRY_PASSWORD }}
          containerAppName: hrispblfrontend
          resourceGroup: hrispbl
          imageToBuild: hrispblregistry.azurecr.io/hrispblfrontend:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


